#!/usr/bin/env python3
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import urlopen, Request

import yaml

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config" / "sources.json"
DATA_DIR = ROOT / "data"
PROJECTS_PATH = DATA_DIR / "projects.md"


def load_sources():
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Missing config file: {CONFIG_PATH}")
    return json.loads(CONFIG_PATH.read_text())


def fetch_yaml(url):
    req = Request(url, headers={"User-Agent": "cncf-opportunities-updater/1.0"})
    with urlopen(req, timeout=30) as response:
        return yaml.safe_load(response)


def iter_items(landscape):
    for category in landscape.get("landscape", []):
        for subcategory in category.get("subcategories", []):
            for item in subcategory.get("items", []):
                if isinstance(item, dict):
                    yield item


def normalize_level(item):
    level = item.get("project") or item.get("cncf_relation") or ""
    if not isinstance(level, str):
        return ""
    level = level.strip().lower()
    if level in {"graduated", "incubating", "sandbox"}:
        return level.title()
    return level.title()


def extract_cncf_projects(landscape):
    projects = {}
    for item in iter_items(landscape):
        name = item.get("name")
        if not name:
            continue
        level = normalize_level(item)
        if level not in {"Graduated", "Incubating", "Sandbox"}:
            continue
        homepage = item.get("homepage_url", "").strip()
        repo = item.get("repo_url", "").strip()
        projects[name] = {
            "name": name,
            "level": level,
            "homepage": homepage,
            "repo": repo,
        }
    return sorted(projects.values(), key=lambda p: p["name"].lower())


def write_projects_markdown(projects):
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# CNCF Projects (Auto-Generated)",
        "",
        "This file is generated by `scripts/update_data.py`. For hand-curated additions or notes, use `data/projects_manual.md`.",
        "",
        f"_Last updated: {timestamp}_",
        "",
        "| Project | CNCF Level | Homepage | Repo |",
        "| --- | --- | --- | --- |",
    ]
    for project in projects:
        name = project["name"]
        level = project["level"]
        homepage = project["homepage"] or ""
        repo = project["repo"] or ""
        lines.append(f"| {name} | {level} | {homepage} | {repo} |")
    PROJECTS_PATH.write_text("\n".join(lines) + "\n")


def main():
    sources = load_sources()
    landscape_url = sources.get("cncf_landscape_yaml")
    if not landscape_url:
        raise KeyError("Missing cncf_landscape_yaml in config/sources.json")
    landscape = fetch_yaml(landscape_url)
    projects = extract_cncf_projects(landscape)
    if not projects:
        print("No CNCF projects found. The landscape format may have changed.", file=sys.stderr)
    write_projects_markdown(projects)
    print(f"Updated {PROJECTS_PATH}")


if __name__ == "__main__":
    main()
